CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE OR REPLACE FUNCTION update_timestamp() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION update_version() RETURNS TRIGGER AS $$
BEGIN
  NEW.version = NEW.version + 1;
  RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;
